# Generated by Django 3.1 on 2020-09-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermall', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=10)),
                ('phone', models.CharField(default='', max_length=11)),
            ],
        ),
    ]
