# Generated by Django 3.1 on 2020-09-01 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermall', '0004_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
