# Generated by Django 3.1 on 2020-09-02 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermall', '0005_auto_20200901_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_description', models.CharField(max_length=5000)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
